name: Basic Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Install Node.js
          uses: actions/setup-node@v5
          with:
              node-version: 22
              cache: 'npm'
              cache-dependency-path: 'github-action/package-lock.json'
        - name: Install dependencies
          working-directory: 'github-action'
          run: npm ci
        - name: Run tests
          working-directory: 'github-action'
          run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Install Node.js
          uses: actions/setup-node@v5
          with:
              node-version: 22
              cache: 'npm'
              cache-dependency-path: 'github-action/package-lock.json'
        - name: Install dependencies
          working-directory: 'github-action'
          run: npm ci
        - name: Deploy application
          working-directory: 'github-action'
          run: echo "Deploying application..."